# Generated by Django 5.2.17 on 2026-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_citation', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_validated', models.BooleanField(default=False)),
                ('question_count', models.PositiveSmallIntegerField(default=59)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('title', 'version'), name='unique_survey_title_version')],
            },
        ),
    ]
