# Generated by Django 5.2.17 on 2026-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_assessement_at',
            new_name='last_assessment_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=5),
        ),
    ]
